5cd40a
8c78a4
function eol_xmlsitemap_cron() {
  116f3 3 8dedada03c4ad1712bed72
0f116f
  $types = array(
    "testimonial",
    f260a670c50a23abe
  );
  if (!file_exists($file)) {
    ac19a 6 cfc75f5fa4e5 b040 d8 6842ac19a8 8cfc 5f5fa4e5
    fclose($file);
  }
  f0f37645ec5e39d79a5c6c386ae1e7
ebf0
  eol_xmlsitemap_cron_add($file,$types);

d3

function eol_xmlsitemap_cron_delete($file) {
  ee1c d b2a d259e0f847be2
  $doc->preserveWhiteSpace = FALSE;
  $doc->load($file);
  82f06b f 8f5 150ac93a91fc6340
  $query = sprintf('//urlset/url[@datasource="xmlsitemap"]');
  foreach($xPath->query($query) as $node) {
    161c79c0cf1ff01334a1436e2055
8a04161c79
  }
  $doc->formatOutput = TRUE;
  d31e41e6cb304977c0e
  return;
}
e24
function eol_xmlsitemap_cron_add($file,$types) {
  if(sizeof($types)<1) return;
  0331 c 240 ba431b076cc412c
  $doc->load( $file, LIBXML_NOBLANKS);
  $xpath = new DOMXPath($doc);
  6a8982846bfebcf7ea b e20adf
  $root = $doc->documentElement;
  $subtype_in_clause = " AND subtype IN (";
  9e897d
  foreach($types AS $v) {
    if($i>0) $subtype_in_clause .= ",";
    895c34f55649c9f838 f8 e61564
24ab8
    $i++;
  }  
  f4f702d3d6e26b971f 97 d4825
  /* id in xmlsitemap is actually nid */
  $result = db_query("SELECT id,loc,priority FROM {xmlsitemap}  WHERE status = 1 AND access=1");
  90cfadab342e885 5d cbdf5 74
    $url = $doc->createElement("url");
    $datasource = $doc->createAttribute("datasource");
    14e0c8b1698b93e316 9 9a5a50a
ba3b14
    $url->appendChild($datasource);
    $xmlsitemap_id = $doc->createAttribute("xmlsitemap_id");
    43a5a418a8e492929f91b 7 2101
afd24
    $url->appendChild($xmlsitemap_id);
//    $loc = $doc->createElement("loc","https://".$_SERVER['HTTP_HOST']."/q/".$row->loc);
    bf40 a 76c094798100905338e22
9305bf40baf76c094798100905338e22
9 05 f40baf76c
    $url->appendChild($loc);
    $priority = $doc->createElement("priority",$row->priority);
    4165fe9a8ed528e2094e7d3dc551
d
    $root->appendChild($url);
  }
  48ec180326fc2b518b  0
}

24f
Deprecated below
*/
b
/**
 * Implements hook_node_insert().
 f6b
function eol_xmlsitemap_node_insert(stdClass $node) {
  return;
935
  eol_xmlsitemap_cron();
  $types = array(
    98bc30a918f79ce
  );
  if(!in_array($node->type,$types) || $node->status!=1) return;
7
  var_dump($node);
  exit;
5fd7813d2195302b4015 d961 8 76e2
5fd7 13d219530 b40 52d961e877 e2
5fd7813 2195302b40152d 61e8776e2
 fd7813d219 302b40152d961 8776e2
5fd7813 2195302b4 152d 61e8776e2
5 d7813d2195 02b40152d961e8 76e2
5fd7813 219530 b40152d961e87 6e2
5f 7813d2195302 40152d 61e8776e2
5fd 813d2195302b401 2d961e8776e2
5 d7813d 195302b40152d 61e8776e2 5fd 813d219530 b40152d96 e 776e2
5fd7813 219530 b40152d961 8776e2 5fd7813d2195 02b40152d 61e877 e2
5fd7813d2 95302b 0152d961e8776e2
5f 7813d2 95302b40152d961e 776e2
 fd7813d219530 b40152d961 8776e2
5fd7813

  $doc = new DOMDocument();
  5794f d d1de2ce7c30fbd23c34c4d
1d5794
  if (!file_exists($file)) {
    $file = fopen($file, 'w') or die("can't open file");
a
    fclose($file);
  }
  bfbc73755fc a3df94 51d72198bc3
5fbfbc
  $doc->formatOutput = true;
  $root = $doc->documentElement;
  c09d c d7b1c77278d506158158dfd
7cc0

  $nid = $doc->createAttribute("nid");
  dc399cee385 0 f60948cc4e70
  $url->appendChild($nid);
  $loc = $doc->createElement("loc","https://".$_SERVER['HTTP_HOST']."/q/node/".$node->nid);
  b1caaf116216b9a0429ec97da
  $priority = $doc->createElement("priority",$node->xmlsitemap["priority"]);
  $url->appendChild($priority);
a
/*
// Create and add href to new link element
75aa0 5 0509df97d59d9e8f4e8989c0
75aa09530509df97d59d9e
$link->appendChild($href);
*/
  ec191d2c8af5aa19e97d5c3525
  $doc->save($file);
}
6471dc4c d2cca6871d5ce6fa4b4b77c
6471dc4c2d2 ca6871 5c


b1
function eol_xmlsitemap_node_delete(stdClass $node) {


